FROM apache/spark:3.4.1

USER root

# Dépendances système
RUN apt-get update && apt-get install -y python3-pip git \
    && pip3 install --upgrade pip

# Dépendances Python (SANS pyspark)
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

